### ISSUE TITLE
Exception processing aggregate files

### ISSUE THREAD

**Issue by ydkhatri** [CrowdStrike/Forensics#13]
Got an exception when running as sudo on local disk on macOS 10.13.
`
[+] Found 4 .core_analytics files to parse.
[+] Found 3 aggregate files to parse.
Traceback (most recent call last):
  File "/Users/research/Desktop/coreanalyticsparser.py", line 231, in <module>
    CoreAnalyticsParser()
  File "/Users/research/Desktop/coreanalyticsparser.py", line 183, in CoreAnalyticsParser
    data_lines = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 17 - 2243)
`

**Comment by monouser7dig** [comment]
same here

**Comment by Security-Sukriti** [comment]
Same.

> Got an exception when running coreAnalyticsParser.py as sudo on local disk on macOS 10.13.
> `[+] Found 4 .core_analytics files to parse. [+] Found 3 aggregate files to parse. Traceback (most recent call last): File "/Users/research/Desktop/coreanalyticsparser.py", line 231, in <module> CoreAnalyticsParser() File "/Users/research/Desktop/coreanalyticsparser.py", line 183, in CoreAnalyticsParser data_lines = json.loads(data) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads return _default_decoder.decode(s) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode raise ValueError(errmsg("Extra data", s, end, len(s))) ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 17 - 2243)`

Same.
